### PR TITLE
Update UI CMS install

### PR DESCRIPTION
**Pull request by AkioSarkiz**
Added simple Render.php, Router.php, Checker.php, Controller.php classes.
Created simple MVC system.
Preview: https://youtu.be/jUOu8eb8gBc

### CODE REVIEW

**Comment by ging-dev** [comment]
Nice, bro

**Comment by batumibiz** [comment]
I don't like step 2 shown in the video, where we have to check the database connection.  
If there is no connection to the database, then all other steps become meaningless (JohnCMS cannot work without a database).  
In the video, along with checking the database, the system administrator data is entered (this should have been done in step 3).

**Comment by AkioSarkiz** [comment]
> 
> 
> I don't like step 2 shown in the video, where we have to check the database connection.
> If there is no connection to the database, then all other steps become meaningless (JohnCMS cannot work without a database).
> In the video, along with checking the database, the system administrator data is entered (this should have been done in step 3).

In the previous version, in step 3, you could write to modify the database data. I simply took these two steps and combined them so that the user could install the CMS faster. The database check was and is in install_script.php. I added Render::html there for a nice display.

```php
if (empty($db_error)) {
        try {
            $pdo = new PDO(
                'mysql:host=' . $db_host . ';dbname=' . $db_name, $db_user, $db_pass,
                [
                    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'UTF8'",
                    PDO::MYSQL_ATTR_USE_BUFFERED_QUERY,
                ]
            );
        } catch (PDOException $e) {
            $pdo_error = $e->getMessage();

            if (stristr($pdo_error, 'no such host')) {
                die(Render::html('error', [
                    'error_title' => Installer::$lang['database'],
                    'error_message' => Installer::$lang['error_db_host'],
                ]));
            } elseif (stristr($pdo_error, 'access denied for user')) {
                die(Render::html('error', [
                    'error_title' => Installer::$lang['database'],
                    'error_message' => Installer::$lang['error_db_user'],
                ]));
            } elseif (stristr($pdo_error, 'unknown database')) {
                die(Render::html('error', [
                    'error_title' => Installer::$lang['database'],
                    'error_message' => Installer::$lang['error_db_name'],
                ]));
            } else {
                die(Render::html('error', [
                    'error_title' => Installer::$lang['database'],
                    'error_message' => Installer::$lang['error_db_unknown'] . ' ' . $pdo_error,
                ]));
            }
        }
    }
```

This is check

**Comment by simba77** [comment]
Sorry, but you were doing a task that was already in progress. At the moment, the new installer is ready.

**Pull request closed without merging**
